import { User, Appointment, MedicalRecord, NotificationItem, FeedbackItem } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'p-1',
    name: 'John Doe',
    email: 'patient@medicare.local',
    phone: '+91 98765 43210',
    password: 'password123',
    hasLoggedIn: false,
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200',
    dob: '15 Mar 1995',
    gender: 'Male',
    address: '123, Green Park, New Delhi, India',
    emergencyContact: '+91 87654 32109',
    emergencyRelation: 'Father',
    bloodGroup: 'B+',
    allergies: 'None Known',
    chronicConditions: 'Hypertension',
    height: '175 cm',
    weight: '70 kg'
  },
  {
    id: 'p-2',
    name: 'Sarah Connor',
    email: 'sarah@example.com',
    phone: '+91 98111 22233',
    password: 'password123',
    hasLoggedIn: false,
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    dob: '28 Jul 1992',
    gender: 'Female',
    address: '45, Palm Street, Bangalore, India',
    emergencyContact: '+91 98222 33344',
    emergencyRelation: 'Sister',
    bloodGroup: 'O+',
    allergies: 'Peanuts',
    chronicConditions: 'Asthma',
    height: '168 cm',
    weight: '62 kg'
  },
  {
    id: 'p-3',
    name: 'Amit Verma',
    email: 'amit.verma@example.com',
    phone: '+91 98765 43211',
    password: 'password123',
    hasLoggedIn: false,
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    dob: '14 Feb 1990',
    gender: 'Male',
    address: 'Sector 62, Noida, India',
    emergencyContact: '+91 98765 43212',
    emergencyRelation: 'Brother',
    bloodGroup: 'A+',
    allergies: 'Penicillin',
    chronicConditions: 'None',
    height: '178 cm',
    weight: '75 kg'
  },
  {
    id: 'p-abhi',
    name: 'abhi',
    email: 'abhi@example.com',
    phone: '+91 98765 43299',
    password: 'password123',
    hasLoggedIn: false,
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    dob: '10 Jan 1996',
    gender: 'Male',
    address: 'Saket, New Delhi, India',
    emergencyContact: '+91 98765 43210',
    emergencyRelation: 'Friend',
    bloodGroup: 'B+',
    allergies: 'None',
    chronicConditions: 'None',
    height: '174 cm',
    weight: '68 kg'
  },
  {
    id: 'd-1',
    name: 'Dr. Ananya Mehta',
    email: 'ananya.mehta@medicare.local',
    phone: '+91 98765 43211',
    password: 'Ananya@123',
    hasLoggedIn: false,
    role: 'doctor',
    specialization: 'Cardiology',
    qualification: 'MBBS, MD',
    experience: 8,
    hospital: 'City Heart Hospital',
    consultationFee: 1000,
    approvalStatus: 'APPROVED',
    rating: 4.8,
    reviewsCount: 320,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    dob: '12 Aug 1982',
    gender: 'Female',
    address: 'Connaught Place, New Delhi'
  },
  {
    id: 'd-2',
    name: 'Dr. Arjun Verma',
    email: 'arjun.verma@medicare.local',
    phone: '+91 98765 43212',
    password: 'Arjun@123',
    hasLoggedIn: false,
    role: 'doctor',
    specialization: 'Neurology',
    qualification: 'MBBS, MD, DM',
    experience: 10,
    hospital: 'NeuroCare Institute',
    consultationFee: 1200,
    approvalStatus: 'APPROVED',
    rating: 4.6,
    reviewsCount: 280,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    dob: '22 Nov 1978',
    gender: 'Male',
    address: 'Saket District Centre, New Delhi'
  },
  {
    id: 'd-3',
    name: 'Dr. Priya Singh',
    email: 'priya.singh@medicare.local',
    phone: '+91 98765 43213',
    password: 'Priya@123',
    hasLoggedIn: false,
    role: 'doctor',
    specialization: 'Dermatology',
    qualification: 'MBBS, MD',
    experience: 6,
    hospital: 'SkinCare Clinic',
    consultationFee: 700,
    approvalStatus: 'APPROVED',
    rating: 4.7,
    reviewsCount: 190,
    avatar: 'https://images.unsplash.com/photo-1527613426441-2da17477166d?auto=format&fit=crop&q=80&w=400',
    dob: '05 Jun 1988',
    gender: 'Female',
    address: 'Sector 18, Noida'
  },
  {
    id: 'd-4',
    name: 'Dr. Rahul Kapoor',
    email: 'rahul.kapoor@medicare.local',
    phone: '+91 98765 43214',
    password: 'Rahul@123',
    hasLoggedIn: false,
    role: 'doctor',
    specialization: 'Orthopedics',
    qualification: 'MBBS, MS',
    experience: 12,
    hospital: 'MediLife Hospital',
    consultationFee: 900,
    approvalStatus: 'APPROVED',
    rating: 4.5,
    reviewsCount: 95,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    dob: '19 Oct 1985',
    gender: 'Male',
    address: 'DLF Phase 3, Gurgaon'
  },
  {
    id: 'd-5',
    name: 'Dr. Sneha Sharma',
    email: 'sneha.sharma@medicare.local',
    phone: '+91 98765 43215',
    password: 'Sneha@123',
    hasLoggedIn: false,
    role: 'doctor',
    specialization: 'Pediatrics',
    qualification: 'MBBS, MD',
    experience: 7,
    hospital: 'Children Care Hospital',
    consultationFee: 800,
    approvalStatus: 'APPROVED',
    rating: 4.2,
    reviewsCount: 40,
    avatar: 'https://images.unsplash.com/photo-1594824813578-834419999a42?auto=format&fit=crop&q=80&w=400',
    dob: '10 Feb 1980',
    gender: 'Female',
    address: 'Vasant Vihar, New Delhi'
  },
  {
    id: 'd-6',
    name: 'Dr. Vikram Joshi',
    email: 'vikram.joshi@medicare.local',
    phone: '+91 98765 43216',
    password: 'Vikram@123',
    hasLoggedIn: false,
    role: 'doctor',
    specialization: 'General Physician',
    qualification: 'MBBS, MD',
    experience: 9,
    hospital: 'City Care OPD',
    consultationFee: 600,
    approvalStatus: 'APPROVED',
    rating: 4.8,
    reviewsCount: 230,
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400',
    dob: '25 Dec 1984',
    gender: 'Male',
    address: 'Defence Colony, New Delhi'
  },
  {
    id: 'a-1',
    name: 'Admin User',
    email: 'admin@medicare.local',
    phone: '+91 90000 00000',
    password: 'password123',
    hasLoggedIn: false,
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'MC-20261001-98721',
    patientId: 'p-abhi',
    patientName: 'abhi',
    patientPhone: '+91 98765 43299',
    doctorId: 'd-3',
    doctorName: 'Dr. Priya Gupta',
    doctorSpecialization: 'Dermatologist',
    doctorAvatar: 'https://images.unsplash.com/photo-1527613426441-2da17477166d?auto=format&fit=crop&q=80&w=400',
    date: '01 Oct 2026',
    time: '10:30 AM',
    type: 'Consultation',
    reason: 'Routine health checkup and consultation',
    status: 'Upcoming',
    createdAt: '2026-09-27'
  },
  {
    id: 'apt-2',
    patientId: 'p-1',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    doctorId: 'd-2',
    doctorName: 'Dr. Rohan Mehta',
    doctorSpecialization: 'General Physician',
    doctorAvatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    date: '12 Oct 2026',
    time: '10:00 AM',
    type: 'In-clinic',
    reason: 'Fever and seasonal flu consultation',
    status: 'Upcoming',
    createdAt: '2026-09-25'
  },
  {
    id: 'apt-1',
    patientId: 'p-1',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    doctorId: 'd-1',
    doctorName: 'Dr. Ananya Sharma',
    doctorSpecialization: 'Cardiologist',
    doctorAvatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
    date: '05 Oct 2026',
    time: '10:30 AM',
    type: 'In-clinic',
    reason: 'Routine cardiac checkup & blood pressure review',
    status: 'Upcoming',
    createdAt: '2026-09-24'
  },
  {
    id: 'apt-3',
    patientId: 'p-1',
    patientName: 'John Doe',
    patientPhone: '+91 98765 43210',
    doctorId: 'd-3',
    doctorName: 'Dr. Priya Gupta',
    doctorSpecialization: 'Dermatologist',
    doctorAvatar: 'https://images.unsplash.com/photo-1594824813578-834419999a42?auto=format&fit=crop&q=80&w=200',
    date: '02 Sep 2026',
    time: '02:00 PM',
    type: 'In-clinic',
    reason: 'Skin allergy and rash checkup',
    status: 'Completed',
    createdAt: '2026-08-30'
  },
  {
    id: 'apt-4',
    patientId: 'p-2',
    patientName: 'Amit Verma',
    patientPhone: '+91 98765 43211',
    doctorId: 'd-2',
    doctorName: 'Dr. Rohan Mehta',
    doctorSpecialization: 'General Physician',
    doctorAvatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    date: '28 Sep 2026',
    time: '11:30 AM',
    type: 'Follow-up',
    reason: 'Blood pressure medication review',
    status: 'Upcoming',
    createdAt: '2026-09-26'
  },
  {
    id: 'apt-5',
    patientId: 'p-3',
    patientName: 'Sneha Patel',
    patientPhone: '+91 98765 43212',
    doctorId: 'd-2',
    doctorName: 'Dr. Rohan Mehta',
    doctorSpecialization: 'General Physician',
    doctorAvatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    date: '28 Sep 2026',
    time: '02:30 PM',
    type: 'In-clinic',
    reason: 'Headache & general fatigue consultation',
    status: 'Upcoming',
    createdAt: '2026-09-26'
  }
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec-1',
    patientId: 'p-1',
    date: '25 Aug 2026',
    type: 'Consultation',
    doctorName: 'Dr. Ananya Sharma',
    description: 'Routine Cardiac Checkup & ECG Review',
    details: 'Patient reports stable vitals. ECG shows normal sinus rhythm. Advised low sodium diet and regular brisk walking.'
  },
  {
    id: 'rec-2',
    patientId: 'p-1',
    date: '10 Jun 2026',
    type: 'Clinical Note',
    doctorName: 'Dr. Rohan Mehta',
    description: 'Cardiovascular Evaluation & Vitals Review',
    details: 'Blood pressure 125/82 mmHg. Pulse 72 bpm. Heart and lung sounds clear. Routine quarterly clinical review completed.'
  },
  {
    id: 'rec-3',
    patientId: 'p-1',
    date: '15 Mar 2026',
    type: 'Clinical Note',
    doctorName: 'Dr. Priya Gupta',
    description: 'Dermatological Clinical Assessment',
    details: 'Patient presented with localized allergic dermatitis. Skin rash resolving satisfactorily under medical supervision.'
  },
  {
    id: 'rec-4',
    patientId: 'p-1',
    date: '05 Jan 2026',
    type: 'Discharge Summary',
    doctorName: 'Dr. Ananya Sharma',
    description: 'Preventive Health Assessment',
    details: 'Overall health status stable. Normal stress test. Follow-up consultation scheduled in 6 months.'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-d3-1',
    userId: 'd-3',
    appointmentId: 'MC-20261001-98721',
    title: 'New Appointment Booked',
    message: 'abhi booked a consultation for 01 Oct 2026 at 10:30 AM.',
    type: 'appointment',
    timestamp: 'Just now',
    read: false
  },
  {
    id: 'notif-1',
    userId: 'p-1',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Ananya Sharma has been confirmed for 05 Oct 2026 at 10:30 AM.',
    type: 'appointment',
    timestamp: '2 mins ago',
    read: false
  },
  {
    id: 'notif-2',
    userId: 'p-1',
    title: 'Appointment Notice',
    message: 'Notice: You have an upcoming consultation with Dr. Rohan Mehta scheduled on your portal.',
    type: 'appointment',
    timestamp: '1 day ago',
    read: false
  },
  {
    id: 'notif-3',
    userId: 'p-1',
    title: 'New Medical Record',
    message: 'Dr. Ananya Sharma has added a new consultation record to your profile.',
    type: 'medical',
    timestamp: '3 days ago',
    read: true
  },
  {
    id: 'notif-4',
    userId: 'p-1',
    title: 'Medical Record Filed',
    message: 'Dr. Priya Gupta has filed your dermatology clinical examination record.',
    type: 'medical',
    timestamp: '5 days ago',
    read: true
  }
];

export const INITIAL_FEEDBACK: FeedbackItem[] = [
  {
    id: 'fb-1',
    patientId: 'p-1',
    patientName: 'John Doe',
    doctorId: 'd-1',
    rating: 5,
    comment: 'Dr. Ananya Sharma is very polite, professional, and thorough with explanations.',
    createdAt: '2026-09-02'
  }
];
