import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Upload, Eye, ArrowLeft, Heart, Shield, Activity, Scale, Download, FileText } from 'lucide-react';

export const MedicalHistoryScreen: React.FC = () => {
  const { currentUser, medicalRecords, addMedicalRecord, goBack } = useApp();
  const [activeTab, setActiveTab] = useState<'All Records' | 'Consultations' | 'Prescriptions' | 'Lab Reports' | 'Clinical Notes' | 'Discharge Summaries'>('All Records');
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [selectedRecordDetail, setSelectedRecordDetail] = useState<any | null>(null);

  // Upload modal state
  const [recordType, setRecordType] = useState<'Consultation' | 'Prescription' | 'Lab Report' | 'Clinical Note' | 'Discharge Summary' | 'General Health'>('Consultation');
  const [recordDate, setRecordDate] = useState('01 Oct 2026');
  const [recordDoctor, setRecordDoctor] = useState('Dr. Rohan Mehta');
  const [recordDesc, setRecordDesc] = useState('');
  const [recordDetails, setRecordDetails] = useState('');
  const [fileName, setFileName] = useState('');

  const userRecords = medicalRecords.filter(r => !currentUser || r.patientId === currentUser.id);

  const filteredRecords = userRecords.filter(r => {
    if (activeTab === 'All Records') return true;
    if (activeTab === 'Consultations') return r.type === 'Consultation';
    if (activeTab === 'Prescriptions') return r.type === 'Prescription';
    if (activeTab === 'Lab Reports') return r.type === 'Lab Report';
    if (activeTab === 'Clinical Notes') return r.type === 'Clinical Note';
    if (activeTab === 'Discharge Summaries') return r.type === 'Discharge Summary';
    return true;
  });

  const handleUploadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentUser) return;
    if (!recordDesc.trim()) {
      alert('Please enter a title for the medical record.');
      return;
    }
    try {
      await addMedicalRecord({
        patientId: currentUser.id,
        date: recordDate,
        type: recordType as any,
        doctorName: recordDoctor,
        description: recordDesc,
        details: recordDetails || (fileName ? `Attached file: ${fileName}` : 'Uploaded medical document')
      });
      setShowUploadModal(false);
      setRecordDesc('');
      setRecordDetails('');
      setFileName('');
      alert('Medical record successfully uploaded and added to your history!');
    } catch (err: any) {
      alert(`Error uploading medical record: ${err.message || 'Failed'}`);
    }
  };

  const handleDownloadRecord = (rec: any) => {
    const content = `MediCare Health Record\nDocument: ${rec.description}\nType: ${rec.type}\nDoctor: ${rec.doctorName}\nDate: ${rec.date}\nClinical Summary & Notes:\n${rec.details || 'None'}\n\nGenerated by MediCare System`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${rec.description.replace(/\s+/g, '_')}_${rec.date}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="w-full px-4 sm:px-8 lg:px-12 py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center space-x-3">
          <button
            onClick={goBack}
            className="p-2 sm:p-2.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 transition shadow-2xs flex items-center justify-center cursor-pointer shrink-0"
            title="Back to Dashboard"
            aria-label="Back to Dashboard"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h2 className="text-2xl font-extrabold text-slate-900 tracking-tight">Medical History & Records</h2>
            <p className="text-sm text-slate-600 mt-1">View & manage medical records, clinical notes, and consultation summaries.</p>
          </div>
        </div>
        <button
          onClick={() => setShowUploadModal(true)}
          className="px-5 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md shadow-blue-500/20 transition flex items-center justify-center space-x-2 cursor-pointer"
        >
          <Upload className="w-4 h-4" />
          <span>Upload Record</span>
        </button>
      </div>

      {/* Health Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-200 flex items-center space-x-4">
          <div className="w-12 h-12 bg-red-50 text-red-600 rounded-xl flex items-center justify-center font-extrabold text-lg">
            <Heart className="w-6 h-6 text-rose-500" />
          </div>
          <div>
            <span className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider">Blood Group</span>
            <span className="text-lg font-extrabold text-slate-900">{currentUser?.bloodGroup || 'B+'}</span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-200 flex items-center space-x-4">
          <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center font-extrabold text-lg">
            <Shield className="w-6 h-6 text-emerald-600" />
          </div>
          <div>
            <span className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider">Allergies</span>
            <span className="text-sm font-extrabold text-slate-900 truncate">{currentUser?.allergies || 'None Known'}</span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-200 flex items-center space-x-4">
          <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-xl flex items-center justify-center font-extrabold text-lg">
            <Activity className="w-6 h-6 text-amber-600" />
          </div>
          <div>
            <span className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider">Chronic Conditions</span>
            <span className="text-xs font-extrabold text-slate-900">{currentUser?.chronicConditions || 'Hypertension'}</span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-200 flex items-center space-x-4">
          <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center font-extrabold text-lg">
            <Scale className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <span className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider">BMI Score</span>
            <span className="text-lg font-extrabold text-slate-900">22.4 <span className="text-[10px] text-emerald-600 font-normal">(Normal)</span></span>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex space-x-2 border-b border-slate-200 pb-4 overflow-x-auto flex-nowrap">
        {(['All Records', 'Consultations', 'Prescriptions', 'Lab Reports', 'Clinical Notes', 'Discharge Summaries'] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-6 py-2.5 rounded-xl text-xs font-bold transition whitespace-nowrap cursor-pointer shrink-0 ${activeTab === tab ? 'bg-blue-600 text-white shadow-md' : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'}`}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Records Table */}
      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-xs font-bold text-slate-500 uppercase tracking-wider">
                <th className="py-4 px-6">Date</th>
                <th className="py-4 px-6">Type</th>
                <th className="py-4 px-6">Doctor</th>
                <th className="py-4 px-6">Description</th>
                <th className="py-4 px-6 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-xs">
              {filteredRecords.length === 0 ? (
                <tr>
                  <td colSpan={5} className="text-center py-12 text-slate-500">
                    No medical records found in this category.
                  </td>
                </tr>
              ) : (
                filteredRecords.map(rec => (
                  <tr key={rec.id} className="hover:bg-slate-50 transition">
                    <td className="py-4 px-6 font-semibold text-slate-900">{rec.date}</td>
                    <td className="py-4 px-6">
                      <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${rec.type === 'Consultation' ? 'bg-blue-100 text-blue-800' : rec.type === 'Clinical Note' ? 'bg-emerald-100 text-emerald-800' : 'bg-purple-100 text-purple-800'}`}>
                        {rec.type}
                      </span>
                    </td>
                    <td className="py-4 px-6 font-semibold text-slate-800">{rec.doctorName}</td>
                    <td className="py-4 px-6 text-slate-600 font-medium">{rec.description}</td>
                    <td className="py-4 px-6 text-right space-x-2">
                      <button
                        onClick={() => setSelectedRecordDetail(rec)}
                        className="px-3.5 py-1.5 bg-blue-50 text-blue-700 hover:bg-blue-100 rounded-lg font-bold transition inline-flex items-center space-x-1 cursor-pointer"
                      >
                        <Eye className="w-3.5 h-3.5" />
                        <span>View</span>
                      </button>
                      <button
                        onClick={() => handleDownloadRecord(rec)}
                        className="px-3.5 py-1.5 bg-slate-100 text-slate-700 hover:bg-slate-200 rounded-lg font-bold transition inline-flex items-center space-x-1 cursor-pointer"
                        title="Download record"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>Download</span>
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Record Details Modal */}
      {selectedRecordDetail && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl shadow-2xl p-6 sm:p-8 max-w-lg w-full space-y-6 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between border-b border-slate-100 pb-4">
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-extrabold text-lg text-slate-900">{selectedRecordDetail.description}</h3>
                  <span className="text-xs font-semibold text-blue-600 uppercase">{selectedRecordDetail.type}</span>
                </div>
              </div>
              <button
                onClick={() => setSelectedRecordDetail(null)}
                className="w-8 h-8 rounded-full bg-slate-100 text-slate-500 hover:bg-slate-200 flex items-center justify-center text-xs font-bold cursor-pointer"
              >
                ✕
              </button>
            </div>

            <div className="space-y-4 text-xs">
              <div className="grid grid-cols-2 gap-4 bg-slate-50 p-4 rounded-2xl border border-slate-100">
                <div>
                  <span className="text-slate-400 font-semibold uppercase text-[10px]">Issued By</span>
                  <p className="font-bold text-slate-800 text-sm mt-0.5">{selectedRecordDetail.doctorName}</p>
                </div>
                <div>
                  <span className="text-slate-400 font-semibold uppercase text-[10px]">Date of Record</span>
                  <p className="font-bold text-slate-800 text-sm mt-0.5">{selectedRecordDetail.date}</p>
                </div>
              </div>

              <div>
                <span className="text-slate-400 font-semibold uppercase text-[10px]">Clinical Summary & Notes</span>
                <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100 text-slate-700 leading-relaxed font-mono whitespace-pre-line mt-1">
                  {selectedRecordDetail.details || 'No additional notes recorded for this document.'}
                </div>
              </div>
            </div>

            <div className="flex justify-between items-center pt-4 border-t border-slate-100">
              <button
                onClick={() => setSelectedRecordDetail(null)}
                className="px-4 py-2 bg-slate-100 text-slate-700 rounded-xl text-xs font-bold hover:bg-slate-200 transition cursor-pointer"
              >
                Close
              </button>
              <button
                onClick={() => handleDownloadRecord(selectedRecordDetail)}
                className="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md transition flex items-center space-x-1.5 cursor-pointer"
              >
                <Download className="w-4 h-4" />
                <span>Download Record</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Upload Record Modal */}
      {showUploadModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl p-6 max-w-lg w-full space-y-4 animate-in fade-in zoom-in-95 duration-150">
            <h3 className="font-bold text-lg text-slate-900">Upload Medical Record</h3>
            <p className="text-xs text-slate-500">Add consultation notes, prescriptions, lab reports, or clinical summaries to your profile.</p>

            <form onSubmit={handleUploadSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Record Type *</label>
                <select
                  value={recordType}
                  onChange={(e) => setRecordType(e.target.value as any)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold"
                >
                  <option value="Consultation">Consultation</option>
                  <option value="Prescription">Prescription</option>
                  <option value="Lab Report">Lab Report</option>
                  <option value="Clinical Note">Clinical Note</option>
                  <option value="Discharge Summary">Discharge Summary</option>
                  <option value="General Health">General Health</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Date *</label>
                  <input
                    type="text"
                    value={recordDate}
                    onChange={(e) => setRecordDate(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold"
                    required
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Doctor Name</label>
                  <input
                    type="text"
                    value={recordDoctor}
                    onChange={(e) => setRecordDoctor(e.target.value)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Title *</label>
                <input
                  type="text"
                  value={recordDesc}
                  onChange={(e) => setRecordDesc(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold"
                  placeholder="e.g., Blood Test Report / Cardiology Prescription"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Description / Notes</label>
                <textarea
                  rows={3}
                  value={recordDetails}
                  onChange={(e) => setRecordDetails(e.target.value)}
                  className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium"
                  placeholder="Enter notes or clinical summary..."
                ></textarea>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">File * (PDF, JPG, PNG)</label>
                <input
                  type="file"
                  accept=".pdf,.jpg,.jpeg,.png"
                  onChange={(e) => {
                    if (e.target.files && e.target.files[0]) {
                      setFileName(e.target.files[0].name);
                    }
                  }}
                  className="w-full text-xs text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-xs file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 cursor-pointer"
                />
                {fileName && <p className="text-[11px] text-emerald-600 font-semibold mt-1">Selected file: {fileName}</p>}
              </div>

              <div className="flex justify-end space-x-2 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setShowUploadModal(false)}
                  className="px-4 py-2 bg-slate-100 text-slate-700 rounded-xl text-xs font-bold cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md cursor-pointer"
                >
                  Upload Record
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
